name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        project: [Unit-Price-Calculator]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Add MSVC to PATH
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@release/v1

      - name: Build
        shell: bash
        run: |
          cd ${{ matrix.project }}
          mkdir build
          case "$RUNNER_OS" in
            "Linux")
              # GCC compiler on Ubuntu
              g++ -std=c++20 -o build/main *.cpp util/*.cpp
              ;;
            "Windows")
              # MSVC compiler on Windows
              cl -EHsc -std:c++20 -W4 -Fe:build/main.exe *.cpp util/*.cpp
              ;;
            "macOS")
              # Clang compiler on macOS
              clang++ -std=c++20 -o build/main *.cpp util/*.cpp
              ;;

          esac